# Generated by Django 5.0.2 on 2024-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('PR_P_CH_DNI', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('PR_CH_TIPODOC', models.CharField(blank=True, max_length=25, null=True)),
                ('PR_CH_APEPAT', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_CH_APEMAT', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_CH_NOM', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_CH_DIR', models.CharField(blank=True, max_length=450, null=True)),
                ('PR_CH_TELEF', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_CH_EMAIL', models.CharField(blank=True, max_length=125, null=True)),
                ('PR_CH_SEXO', models.CharField(blank=True, max_length=1, null=True)),
                ('PR_DT_FECNAC', models.CharField(blank=True, max_length=20, null=True)),
                ('PR_CH_EST', models.CharField(default='activo', max_length=10)),
            ],
            options={
                'db_table': 'Personas',
            },
        ),
    ]
