# Generated by Django 5.0.2 on 2024-06-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('PR_IN_IDPK_Dis', models.AutoField(primary_key=True, serialize=False)),
                ('PR_CH_Nombre_Dis', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_CH_EST', models.CharField(default='activo', max_length=10)),
            ],
            options={
                'db_table': 'Distritos',
            },
        ),
    ]
