# Generated by Django 5.0.2 on 2024-06-10 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncidenciasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('PR_IN_IDPK_Dir', models.AutoField(primary_key=True, serialize=False)),
                ('PR_CH_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_CH_avenida', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_CH_pasaje', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_CH_jiron', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_CH_zona', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_TE_referencia', models.TextField(blank=True, null=True)),
                ('PR_CH_EST', models.CharField(default='activo', max_length=10)),
                ('PR_CH_Nombre_Dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncidenciasApp.distritos')),
            ],
            options={
                'db_table': 'Direcciones',
            },
        ),
    ]
