# Generated by Django 5.0.2 on 2024-06-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncidenciasApp', '0002_direcciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='PR_CH_Nombre_Dis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
