# Generated by Django 5.0.2 on 2024-07-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IncidenciasApp', '0004_incidencias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencias',
            options={'managed': False},
        ),
    ]
